name: self-serve deployer


on:
  push:
    branches: [deploy-prod]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        run: |
          cd server
          npm install
          PORT=80 JWT_SECRET=123456 PASSWORD_SALT=mysecretsalt ENV=production npm run start:prod

