name: self-serve deployer


on:
  push:
    branches: [deploy-prod]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout repo+branch
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install and build server
        run: |
          cd server
          npm install
      - name: restart server
        env:
          DB_PATH: ${{ secrets.DB_PATH }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PASSWORD_SALT: ${{ secrets.PASSWORD_SALT }}
          ENV: ${{ secrets.ENV }}
          PORT: ${{ secrets.PORT }}
        run: |
          cd server
          npm run start:prod
